# Generated by Django 3.2.3 on 2021-05-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210518_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
