# Generated by Django 3.2.3 on 2021-05-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210518_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='qr_code',
        ),
    ]
