# Generated by Django 3.2.3 on 2021-05-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210515_0524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
