# Generated by Django 2.2.14 on 2021-05-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_order_ref_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='one_click_purchasing',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_customer_id',
        ),
    ]
